item {
  id: 1
  name: 'power cube'
}

item {
  id: 2
  name: 'switch'
}

item {
  id: 3
  name: 'switch/side'
}

item {
  id: 4
  name: 'robot'
}

item {
  id: 5
  name: 'scale'
}

item {
  id: 6
  name: 'scale/side'
}

